version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5454:5432
    env_file:
      - .env
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata:
    driver: local