version: '3.7'

services:
  database:
    image: postgres
    container_name: car-rentalls-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - ${PG_PORT}:${PG_PORT}
    command: -p ${PG_PORT}
    volumes:
      - pg_data:/data/postgres
    networks:
      - car_rentalls_env_nw

  redis:
    image: redis:alpine
    container_name: car-rentalls-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - car_rentalls_env_nw

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  car_rentalls_env_nw:
