name: CI
 
 
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          
      - name: Install Depedencies 
        run: yarn
        
      - name: Build
        run: yarn build
        
      - name: Copy dist to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{secrets.SSH_KEY}}
          command_timeout: 2m
          source: ".,!node_modules"
          target: "test"
